module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'js', 'json'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.[tj]sx?$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.entity.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.enum.ts',
    '!src/**/*.interface.ts',
    '!src/**/index.ts',
    '!src/main.ts',
  ],
  collectCoverage: true,
  coverageDirectory: './coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
    '^test/(.*)$': '<rootDir>/test/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/test/jest-setup.ts'],
  testTimeout: 15000,
  forceExit: true,
  detectOpenHandles: true,
  verbose: true,
  transformIgnorePatterns: [
    'node_modules/(?!(.*\\.mjs$|@nestjs/mapped-types|@nestjs/.*))'
  ],
  testPathIgnorePatterns: [
    "/node_modules/",
    "auth.service.spec.ts",
    "auth.controller.spec.ts",
    "marca.controller.spec.ts",
    "producto.controller.spec.ts",
    "condicion-iva.controller.spec.ts",
    "proveedor-operacion.controller.spec.ts",
    "personal.controller.spec.ts",
    "linea.controller.spec.ts",
    "localidad.controller.spec.ts",
    "provincia.controller.spec.ts",
    "empresa.controller.spec.ts",
    "domicilio.controller.spec.ts",
    "cliente.controller.spec.ts",
    "rol.controller.spec.ts",
  ], 
};
  